# device config for RadiaCode 101/102/103/103G and 110 Gamma Spectrometer

# returns gamma counts and dose calculated from spectrum in 1cmÂ³ CsJ(Tl) crystal

DAQModule: RC1xxConfig

# other options:
# bluetooth_mac:   xxxx    # bluetooth MAC of device
# reset:  false            # default: true, reset device memory on start
show_spectrum:   true    # default: false, return full spectrum


